version: "3.9"

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    working_dir: /workspace
    environment:
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - GITHUB_RELEASE_ACCESS_TOKEN
