steps:
  - name: ":test_tube: Test"
    key: test
    plugins:
      - docker#v2.0.0:
          image: "golang:1.20"
          command: ["go", "test", "-v", "-race", "."]
          environment:
            - GO111MODULE=on

  - name: ":golang: Compile"
    key: build
    plugins:
      - golang-cross-compile#v1.3.0:
          build: main.go
          import: github.com/buildkite/buildkite-agent-metrics
          targets:
            - version: "1.20.2"
              goos: linux
              goarch: amd64
              gomodule: "on"
            - version: "1.20.2"
              goos: linux
              goarch: arm64
              gomodule: "on"
            - version: "1.20.2"
              goos: windows
              goarch: amd64
              gomodule: "on"
            - version: "1.20.2"
              goos: darwin
              goarch: amd64
              gomodule: "on"
            - version: "1.20.2"
              goos: darwin
              goarch: arm64
              gomodule: "on"

  - name: ":lambda: Build Lambda"
    key: build-lambda
    command: .buildkite/steps/build-lambda.sh

  - name: ":s3: Upload to S3"
    key: upload-to-s3
    depends_on:
      - test
      - build-lambda
    command: ".buildkite/steps/upload-to-s3.sh"
    branches: master
    agents:
      queue: "elastic-runners"
    concurrency: 1
    concurrency_group: "release_buildkite_metrics_s3"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-metrics

  - name: ":pipeline:"
    key: upload-release-steps
    depends_on:
      - build
      - upload-to-s3
    command: .buildkite/steps/upload-release-steps.sh
