steps:
  -
    name: "📦"
    command: "make build"
    artifact_paths: "build/*"
    plugins:
      docker-compose:
          run: build

  - wait

  -
    name: "Release to :s3:"
    command: ".buildkite/upload.sh"
    branches: "master"
    agents:
      queue: "deploy"
