steps:
  - block: ":rocket: Release ${VERSION}?"

  - label: ":s3:"
    command: ".buildkite/steps/release-s3-version.sh"
    agents:
      queue: "elastic-runners"
    concurrency: 1
    concurrency_group: 'release_buildkite_metrics_github'
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-metrics

  - label: ":github:"
    command: ".buildkite/steps/release-github.sh"
    agents:
      queue: "elastic-runners"
    concurrency: 1
    concurrency_group: 'release_buildkite_metrics_github'
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-agent-metrics
      - aws-ssm#v1.0.0:
          parameters:
            GITHUB_RELEASE_ACCESS_TOKEN: /pipelines/buildkite-agent-metrics/GITHUB_RELEASE_ACCESS_TOKEN
      - ecr#v2.0.0:
          login: true
          account-ids: "445615400570"
      - docker#v3.5.0:
          image: "445615400570.dkr.ecr.us-east-1.amazonaws.com/deploytools:2020.03"
          propagate-environment: true

