steps:
  - name: ":hammer_and_wrench:"
    command: "make test"
    plugins:
      - docker-compose:
          run: "golang"

  - wait

  - name: ":golang:"
    command: "make build"
    artifact_paths: "build/*"
    plugins:
      - docker-compose:
          run: "golang"

  - name: ":lambda:"
    command: "make build-lambda"
    artifact_paths: "build/*"

  - wait

  - name: "Release to :s3:"
    command: ".buildkite/upload.sh"
    branches: "master,publish-lambda-to-all-regions"
    agents:
      queue: "deploy"
    concurrency: 1
    concurrency_group: 'release_to_s3'

