steps:
  - name: ":hammer_and_wrench:"
    plugins:
      - docker#v2.0.0:
          image: "golang:1.11"
          command: ["go", "test", "-v", "-race", "."]
          environment:
            - GO111MODULE=on

  - wait
  - name: ":golang: :pipeline:"
    plugins:
      - golang-cross-compile#v1.3.0:
          build: main.go
          import: github.com/buildkite/buildkite-agent-metrics
          targets:
            - version: "1.11"
              goos: linux
              goarch: amd64
              gomodule: "on"
            - version: "1.11"
              goos: windows
              goarch: amd64
              gomodule: "on"
            - version: "1.11"
              goos: darwin
              goarch: amd64
              gomodule: "on"

  - name: ":lambda:"
    command: .buildkite/steps/build-lambda.sh

  - wait
  - name: ":pipeline:"
    command: .buildkite/steps/upload-release-steps.sh


