steps:
  - name: ":hammer_and_wrench:"
    command: "make test"
    plugins:
      - docker-compose:
          run: "golang"

  - wait

  - name: ":mac: amd64"
    command: .buildkite/steps/build-binary.sh darwin amd64

  - name: ":linux: amd64"
    command: .buildkite/steps/build-binary.sh linux amd64

  - name: ":lambda:"
    command: .buildkite/steps/build-lambda.sh

  - wait

  - name: "Release to :s3:"
    command: ".buildkite/upload.sh"
    branches: master
    agents:
      queue: "deploy"
    concurrency: 1
    concurrency_group: 'release_to_s3'



