steps:
  -
    name: "📦"
    command: "make build"
    artifact_paths: "build/*"
    plugins:
      - ssh://git@github.com/buildkite/plugins/docker-compose:
          container: "build"

  - wait

  -
    name: "Release to :s3:"
    command: ".buildkite/upload.sh"
    branches: "master"
    agents:
      queue: "deploy"
