steps:
  - name: ":hammer_and_wrench:"
    command: ".buildkite/steps/test.sh"

  - wait

  - name: ":mac: amd64"
    command: .buildkite/steps/build-binary.sh darwin amd64

  - name: ":linux: amd64"
    command: .buildkite/steps/build-binary.sh linux amd64

  - name: ":lambda:"
    command: .buildkite/steps/build-lambda.sh

  - wait

  - block
  - name: ":s3: :rocket:"
    command: ".buildkite/steps/upload.sh"
    branches: master
    agents:
      queue: "deploy"
    concurrency: 1
    concurrency_group: 'release_to_s3'

